"""
This module implements the algorithms for sampling uniformly random linear codes with a specified hull dimension,
presented in [EC:AlbBenLai25]. The main function to do this is SampleCode(n,k,h,q).

The module also implements some standard operations such as computing the dual, the closure, and the
hull, along with some non-standard operations such as the signed closure, and "dehulling" a code, that
is computing a basis of the subcode T <= C such that C = T + hull(C).
"""
from sage.all import (
    GF,
    Permutation,
    PolynomialRing,
    RR,
    identity_matrix,
    is_prime_power,
    matrix,
    random_matrix,
    random_vector,
    span,
    vector,
)
from sage.all import randint, random, shuffle
from sage.all import copy

import sys

# utility functions

def _cprod(a, b):
    """
    Entry-wise multiplication of vectors.
    """
    assert len(a) == len(b)
    return vector([a[i] * b[i] for i in range(len(a))])


# basic samplers

def random_bit():
    """
    Random bit {0,1} as int.
    """
    return randint(0, 1)


def random_invertible(q):
    """
    Return a random element of FF_q^*.
    """
    F = GF(q)
    z = F.multiplicative_generator()
    i = randint(1, q-1)
    return z ** i


def random_fullrank_matrix(n, q):
    """
    Return a random full-rank n x n matrix over FF_q.
    """
    while True:
        A = random_matrix(GF(q), n, n)
        if A.rank() == n:
            return A


def random_permutation_matrix(n):
    """
    Return a random element from the group P_n(ZZ).
    """
    ind = list(range(1, n+1))
    shuffle(ind)
    return Permutation(ind).to_matrix()


def random_signed_permutation_matrix(n):
    """
    Return a random element from the group O_n(ZZ).
    """
    P = random_permutation_matrix(n)
    v = vector([(-1) ** random_bit() for i in range(n)])
    return matrix([_cprod(p, v) for p in P])


def random_monomial_matrix(n, q):
    """
    Return a random element from the group M_n(FF_q).
    """
    P = random_permutation_matrix(n)
    v = vector([random_invertible(q) for i in range(n)])
    return matrix([_cprod(p, v) for p in P])


# sanity check

def _check_code(A, n=None, k=None, q=None):
    """
    Return parameters n,k,F of [n,k]-linear code over F, and check health. Optional parameters
    override reality.
    """
    if n is None:
        n = A.ncols()
    if k is None:
        k = A.nrows()
    F = None
    if q is None:
        F = A.base_ring()
    else:
        assert is_prime_power(q)
        F = GF(q)
    assert n >= k
    assert A.rank() == k
    assert F.is_field()
    assert F.is_finite()
    return n, k, F


# algorithms on linear codes

def dual(A, q=None):
    """
    Given a row generator matrix for a [n,k]-linear code over a finite field F, return a
    generator matrix of its dual.
    """
    n, k, F = _check_code(A, q=q)
    # compute SF and correct it into [I | M] with a permutation P
    A_ = A.echelon_form()
    perm = [i for i in A_.pivots()] + [i for i in range(n) if i not in A_.pivots()]
    P = Permutation([p + 1 for p in perm]).to_matrix()
    assert (A_ * P).matrix_from_columns(range(k)) == 1
    # dual is then [-M^T | I] corrected by the permutation P^T
    M = (A_ * P).matrix_from_columns(range(k, n))
    M_ = (-M.T).augment(identity_matrix(F, n - k))
    assert M_ * (A_ * P).T == 0
    return M_ * P.T


def hull(A):
    """
    Given a row generator matrix for a [n,k]-linear code over a finite field F, return a
    generator matrix of its hull.
    """
    _ = _check_code(A)
    M = A.stack(dual(A))
    H = M.right_kernel().basis_matrix()
    return H


def hulldim(A):
    """
    Compute hull dimension of the linear code generated by A.
    """
    _, k, _ = _check_code(A)
    return k - (A * A.T).rank()


def dehull(A):
    """
    Given an [n,k]-linear h-hollow code A with hull H, compute a [n,k]-linear 0-hollow code T such
    that A = H + T algebraically. Returns (T, H).

    EXAMPLES:
        sage: import selforthogonal as so
        sage: A = so.SampleCode(16, 8, 4, 41)
        sage: T, H = so.dehull(A)
        sage: assert span(A) == span(T) + span(H)
        sage: assert span(H) == span(so.hull(A))
    """
    _, k, F = _check_code(A)

    H = hull(A)
    h = H.nrows()
    # edgecases
    if h == 0:
        return (A, H)
    if h == k:
        return (matrix(F, []), A)

    # compute basis of A/hull(A) and lift to A
    V = span(A)
    W = span(H)
    Q = V / W
    T = matrix(F, [Q.lift(b) for b in Q.basis()])

    assert hulldim(T) == 0
    return (T, H)


# various closures

def closure(A):
    """
    Given a row generator matrix for a [n,k]-linear code over a finite field F, return a
    generator matrix for its closure.
    """
    _, _, F = _check_code(A)
    A_ = copy(A)
    for x in F:
        if x == 0 or x == 1:
            continue
        A_ = A_.augment(x * A)
    return A_


def signed_closure(A):
    """
    Given a row generator matrix for a [n,k]-linear code over a finite field F, return a
    generator matrix for its signed closure.
    """
    _ = _check_code(A)
    A_ = copy(A)
    A_ = A_.augment(-1 * A)
    return A_


def _QR(F):
    """
    Output the list of all distinct quadratic residues of the finite field F.
    """
    return [x for x in F if x.is_square()]


# samplers for hollow codes

def MaxSols(D, F):
    """
    Return the maximal number of solutions a smooth conic with discriminant D over the finite field
    F can have.

    [EC:AlbBenLai25]: Fig. 3
    """
    assert D != 0
    assert D in F
    q = len(F)
    return 2 * q - 1 if D in _QR(F) else q + 1


def SampleSelfOrthogonal(A, halt=128, n=None, q=None):
    """
    Sample a uniformly random self-orthogonal vector from a code generated by A.

    EXAMPLES:
        sage: import selforthogonal as so
        sage: A = random_matrix(GF(41), 8, 16)
        sage: v = so.SampleSelfOrthogonal(A)  # sample s.o. vector v from Span(A) <= FF_{41}^{16}
        sage: assert v * v == 0
        sage: assert v in span(A)
        sage:
        sage: v = so.SampleSelfOrthogonal(identity_matrix(GF(41), 16))  # sample s.o. vector v from FF_{41}^{16}
        sage: v = so.SampleSelfOrthogonal([], n=16, q=41)  # this does the same thing
        sage: assert v * v == 0

    [EC:AlbBenLai25]: Def. 10, Lem. 5, Fig. 3
    """
    # edge case to just return a random so vector if A is empty
    if not A:
        if n is None or q is None:
            return None
        assert n > 0
        assert q.is_prime_power()
        A = identity_matrix(GF(q), n)
    _, k, F = _check_code(A)

    # reorder basis to get smooth conic
    G = copy(A)
    v, w = G[k-2], G[k-1]
    D = (v*w)**2 - (v*v) * (w*w)
    if D == 0:
        found = False
        for i in range(k):
            for j in range(i+1, k):
                v, w = G[i], G[j]
                D = (v*w)**2 - (v*v) * (w*w)
                if D != 0:
                    found = True
                    break
            if found:
                break
        G[i], G[k-2] = G[k-2], G[i]
        G[j], G[k-1] = G[k-1], G[j]

    # set max number of solutions
    M = MaxSols(D, F)

    R, X = PolynomialRing(F, "X").objgen()
    for i in range(halt):
        pre_x = [F.random_element() for i in range(k-2)]
        # find all conic solutions
        roots = []
        for a in F:
            x = vector(R, pre_x + [a, X])
            # We must exclude the zero case
            polynomial = x * G * G.T * x
            if not polynomial:
                continue
            rs = polynomial.roots(multiplicities=False)
            for r in rs:
                roots.append((a, r))
        L = len(roots)
        # assert L in {M, M-len(F)} # Commented since it cause some issues
        # possibly reject
        if random() > L / M:
            continue
        # sample random solution
        sol = list(roots[randint(0, L-1)])
        # construct so vector
        cs = vector(F, pre_x + sol)
        v = cs * G
        assert v * v == 0
        return v
    return None


def SampleCode(n, k, h, q, randomize=True, verbose=False):
    """
    Returns a random [n,k]-linear code over FF_q with 2*k <= n and hull dimension h <= k.

    EXAMPLES:
        sage: import selforthogonal as so
        sage: A = so.SampleCode(16, 8, 4, 41)  # sample 8-dim. subspace of FF_{41}^{16} with hull dim. 4
        sage: assert so.hulldim(A) == 4
        sage:
        sage: A = so.SampleCode(16, 8, 4, 41, randomize=False)  # get hull basis as last 4 rows
        sage: H = so.hull(A)
        sage: assert span(A[4:]) == span(H)

    [EC:AlbBenLai25]: Def. 11, Lem. 6, Fig. 3
    """
    assert k >= 1
    assert h >= 0
    # proof of Lem. 6 requires 2*h <= k, but this also works
    assert h <= k
    assert 2 * k <= n
    F = GF(q)

    # sample trivial hull part
    vs = []
    for i in range(k - h):
        v = random_vector(F, n)
        vs.append(v)

    # check rank and hull dimension
    A_0 = matrix(F, vs)
    if A_0.rank() != k - h:
        return None
    if hulldim(A_0) != 0:
        return None

    # sample hull part
    A_i = A_0
    for i in range(h):
        if verbose:
            sys.stdout.write(f"\rSampling a random self-orthogonal code: {i}/{h}")
            sys.stdout.flush()
        # sample new hull vector
        v = SampleSelfOrthogonal(dual(A_i, q=q), halt=n, n=n, q=q)
        if v is None:
            return None
        vs.append(v)
        # check rank increments
        A_i = matrix(F, vs)
        if A_i.rank() != k - h + i + 1:
            return None
    A_h = A_i
    assert A_h.rank() == k
    assert hulldim(A_h) == h
    print('\n')

    # optionally randomise basis
    S = random_fullrank_matrix(k, len(F)) if randomize else 1
    return S * A_h


def random_selforthogonal_code(n, k, q, verbose=False):
    """
    Return a random self-orthogonal i.e. weakly self-dual [n,k]-linear code over FF_q.
    """
    while(1):
        try:
            return SampleCode(n, k, k, q, verbose=verbose)
        except:
            print("Sample Code failed")


# misc

def prob_hull(n, k, h, q):
    """
    Returns the probability that a uniformly random [n,k]-linear code over FF_q has hull dimension h.

    Sendrier (1997): On the Dimension of the Hull, Thm. 4.18
    """
    p = RR(1)
    p /= q ** (h * (h + 1) / 2)
    for i in range(k - h):
        p *= (RR(1) - (RR(1) / (q ** (k - i))))
    for i in range(1, ((k - h) // 2) + 1):
        p /= (RR(1) - (RR(1) / (q ** (2*i))))
    return p